"""Generate the dialog skin XML files.

They share a panel, header, accent rule and button styling, so they are
generated from one template rather than five hand-maintained copies that drift.
Run after changing the look:

    py -3 tools/make_dialog_skins.py
"""
import sys
from pathlib import Path

SKIN = Path(__file__).resolve().parents[1] / "plugin.video.grnshows/resources/skins/Default/1080i"

ACCENT = "FF34D399"
PANEL = "F81B1D22"
HEADER = "FF12141A"
TEXT = "FFD2D6DC"
MUTED = "FF8A8F9A"


def shell(width, height, body, heading_font="font14"):
    """Dim background, centred panel, header bar, accent rule, then body."""
    x, y = (1920 - width) // 2, (1080 - height) // 2
    return """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/make_dialog_skins.py. Edit that, not this file. -->
<window>
  <defaultcontrol always="true">%(default)s</defaultcontrol>
  <coordinates><system>1</system><posx>0</posx><posy>0</posy></coordinates>
  <controls>
    <control type="image">
      <posx>0</posx><posy>0</posy><width>1920</width><height>1080</height>
      <texture>DialogBack.png</texture><colordiffuse>D8000000</colordiffuse>
    </control>
    <control type="group">
      <posx>%(x)s</posx><posy>%(y)s</posy>
      <control type="image">
        <posx>0</posx><posy>0</posy><width>%(w)s</width><height>%(h)s</height>
        <texture border="2">white.png</texture><colordiffuse>%(panel)s</colordiffuse>
      </control>
      <control type="image">
        <posx>0</posx><posy>0</posy><width>%(w)s</width><height>78</height>
        <texture border="2">white.png</texture><colordiffuse>%(header)s</colordiffuse>
      </control>
      <control type="label" id="3000">
        <posx>32</posx><posy>18</posy><width>%(hw)s</width><height>42</height>
        <font>%(hf)s</font><textcolor>FFFFFFFF</textcolor><label></label>
      </control>
      <control type="image">
        <posx>0</posx><posy>78</posy><width>%(w)s</width><height>2</height>
        <texture>white.png</texture><colordiffuse>%(accent)s</colordiffuse>
      </control>
%(body)s
    </control>
  </controls>
</window>
""" % {"x": x, "y": y, "w": width, "h": height, "hw": width - 64, "hf": heading_font,
       "panel": PANEL, "header": HEADER, "accent": ACCENT, "body": body,
       "default": BODY_DEFAULT.get(id(body), 10)}


BODY_DEFAULT = {}


def button(control_id, x, y, width, label, on_left=None, on_right=None):
    nav = ""
    if on_left:
        nav += "<onleft>%s</onleft>" % on_left
    if on_right:
        nav += "<onright>%s</onright>" % on_right
    return """      <control type="button" id="%(id)s">
        <posx>%(x)s</posx><posy>%(y)s</posy><width>%(w)s</width><height>56</height>
        <font>font13</font><align>center</align><aligny>center</aligny>
        <textcolor>%(text)s</textcolor><focusedcolor>FF12141A</focusedcolor>
        <texturefocus border="2" colordiffuse="%(accent)s">white.png</texturefocus>
        <texturenofocus border="2" colordiffuse="22FFFFFF">white.png</texturenofocus>
        <label>%(label)s</label>%(nav)s
      </control>""" % {"id": control_id, "x": x, "y": y, "w": width, "label": label,
                       "text": TEXT, "accent": ACCENT, "nav": nav}


def textbox(control_id, x, y, width, height, font="font13", colour=TEXT):
    return """      <control type="textbox" id="%s">
        <posx>%s</posx><posy>%s</posy><width>%s</width><height>%s</height>
        <font>%s</font><textcolor>%s</textcolor><label></label>
      </control>""" % (control_id, x, y, width, height, font, colour)


def write(name, xml, default_control):
    xml = xml.replace("<defaultcontrol always=\"true\">10</defaultcontrol>",
                      "<defaultcontrol always=\"true\">%s</defaultcontrol>" % default_control)
    path = SKIN / name
    path.write_text(xml, encoding="utf-8", newline="\n")
    return path


def main():
    SKIN.mkdir(parents=True, exist_ok=True)
    written = []

    # ok.xml -------------------------------------------------------------
    body = "\n".join([textbox(3010, 32, 104, 656, 150), button(10, 470, 276, 218, "OK")])
    written.append(write("ok.xml", shell(720, 360, body), 10))

    # confirm.xml --------------------------------------------------------
    body = "\n".join([textbox(3010, 32, 104, 656, 150),
                      button(10, 244, 276, 218, "OK", on_right=11),
                      button(11, 470, 276, 218, "Cancel", on_left=10)])
    written.append(write("confirm.xml", shell(720, 360, body), 11))

    # textviewer.xml -----------------------------------------------------
    body = "\n".join([textbox(3010, 40, 104, 1200, 620, font="font12", colour=TEXT),
                      button(10, 551, 744, 218, "Close")])
    written.append(write("textviewer.xml", shell(1280, 828, body), 10))

    # progress.xml -------------------------------------------------------
    body = "\n".join([
        textbox(3010, 32, 104, 836, 96, colour=TEXT),
        """      <control type="label" id="3020">
        <posx>32</posx><posy>206</posy><width>836</width><height>34</height>
        <font>font12</font><textcolor>%s</textcolor><label></label>
      </control>""" % ACCENT,
        """      <control type="progress" id="3030">
        <posx>32</posx><posy>252</posy><width>836</width><height>16</height>
      </control>""",
        button(11, 651, 296, 218, "Cancel")])
    written.append(write("progress.xml", shell(900, 384, body), 11))

    # select.xml ---------------------------------------------------------
    body = "\n".join(["""      <control type="list" id="2025">
        <posx>20</posx><posy>96</posy><width>1000</width><height>620</height>
        <onup>2025</onup><ondown>2025</ondown><onleft>11</onleft><onright>10</onright>
        <pagecontrol>60</pagecontrol>
        <itemlayout height="60" width="1000">
          <control type="image">
            <posx>16</posx><posy>18</posy><width>24</width><height>24</height>
            <texture>OverlayWatched.png</texture><colordiffuse>%(accent)s</colordiffuse>
            <visible>String.IsEqual(ListItem.Property(check_status),checked)</visible>
          </control>
          <control type="label">
            <posx>56</posx><posy>0</posy><width>620</width><height>60</height>
            <font>font13</font><textcolor>%(text)s</textcolor><aligny>center</aligny>
            <label>$INFO[ListItem.Label]</label>
          </control>
          <control type="label">
            <posx>984</posx><posy>0</posy><width>300</width><height>60</height>
            <font>font12</font><textcolor>%(muted)s</textcolor><align>right</align><aligny>center</aligny>
            <label>$INFO[ListItem.Label2]</label>
          </control>
        </itemlayout>
        <focusedlayout height="60" width="1000">
          <control type="image">
            <posx>0</posx><posy>2</posy><width>1000</width><height>56</height>
            <texture border="2">white.png</texture><colordiffuse>2634D399</colordiffuse>
          </control>
          <control type="image">
            <posx>0</posx><posy>2</posy><width>4</width><height>56</height>
            <texture>white.png</texture><colordiffuse>%(accent)s</colordiffuse>
          </control>
          <control type="image">
            <posx>16</posx><posy>18</posy><width>24</width><height>24</height>
            <texture>OverlayWatched.png</texture><colordiffuse>%(accent)s</colordiffuse>
            <visible>String.IsEqual(ListItem.Property(check_status),checked)</visible>
          </control>
          <control type="label">
            <posx>56</posx><posy>0</posy><width>620</width><height>60</height>
            <font>font13</font><textcolor>FFFFFFFF</textcolor><aligny>center</aligny>
            <label>$INFO[ListItem.Label]</label>
          </control>
          <control type="label">
            <posx>984</posx><posy>0</posy><width>300</width><height>60</height>
            <font>font12</font><textcolor>%(accent)s</textcolor><align>right</align><aligny>center</aligny>
            <label>$INFO[ListItem.Label2]</label>
          </control>
        </focusedlayout>
      </control>
      <control type="scrollbar" id="60">
        <posx>1026</posx><posy>96</posy><width>10</width><height>620</height>
        <onleft>2025</onleft><showonepage>false</showonepage><orientation>vertical</orientation>
      </control>""" % {"accent": ACCENT, "text": TEXT, "muted": MUTED},
        button(12, 20, 736, 200, "Select all", on_right=13),
        button(13, 232, 736, 200, "Clear", on_left=12, on_right=10),
        button(10, 610, 736, 200, "OK", on_left=13, on_right=11),
        button(11, 822, 736, 200, "Cancel", on_left=10)])
    written.append(write("select.xml", shell(1060, 820, body), 2025))

    for path in written:
        print("wrote %-18s %5d bytes" % (path.name, path.stat().st_size))
    return 0


if __name__ == "__main__":
    sys.exit(main())
